### ISSUE TITLE
Final boss spell steal channel time is wrong

### ISSUE THREAD

**Issue by fry-** [arcadia-redux/pathfinder_issues#103]
When you click on the final boss while he channels for the spell steal, you can see how much time is left for the channeling to finish.
The channeling time shown is wrong though. Channeling ends when the timer shows 2.x seconds left.
This way, it is hard to know when to use Eul's to not get your spell stolen.

**Comment by fcalife** [comment]
This change wasn't very popular with the community when asked about it
