### ISSUE TITLE
Phoenix's lvl 25 30% cdr talent doesn't stack with other cdr

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/pathfinder_issues#119]

**Comment by lovro-m** [comment]
Please check my CD reduction PR and give feedback @Draze22 if you agree with it.

**Comment by Draze22** [comment]
> Please check my CD reduction PR and give feedback @Draze22 if you agree with it.

Made a few changes, looks good.

**Comment by fcalife** [comment]
Fixed by @lovro-m
