### ISSUE TITLE
Some enemies might be able to pierce/dispel 100% damage reduction

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/pathfinder_issues#129]
![image](https://user-images.githubusercontent.com/63279022/140445842-3af30741-a993-4455-8194-9b62419a53d8.png)

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **7** days with label "needs confirmation".  
It will be **closed** automatically after **7** days if this issue stays inactive.
