### ISSUE TITLE
Players are still getting stuck in trap rooms because of disconnected players

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/pathfinder_issues#130]
![image](https://user-images.githubusercontent.com/63279022/140446198-e6fd1904-9e83-4f2e-8683-dad007d07a28.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/140845221-35cd1f55-f1bc-48f5-9a9f-d8e8c4ed926c.png)

**Comment by fcalife** [comment]
duplicate of https://github.com/arcadia-redux/pathfinder_issues/issues/114
