### ISSUE TITLE
Split Shot destroys boxes

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/pathfinder_issues#131]
![image](https://user-images.githubusercontent.com/63279022/140676238-70d90e59-3c6c-433b-abfc-44efa791bd1d.png)

**Comment by SanctusAnimus** [comment]
Why is it not good and how does that make any difference

**Comment by Snoresville** [comment]
think of your team, if you eat all of the potions at full health and mana before your team gets nuked and has no mana, how else would they recover?

**Comment by fcalife** [comment]
there's also the troll/beastmaster room, where destroying boxes actively kills you faster
