### ISSUE TITLE
Gorgon Eyes causes enemies to (Sometimes?) perma aggro Medusa

### ISSUE THREAD

**Issue by NocturneOfShadows** [arcadia-redux/pathfinder_issues#136]
![Screenshot_134](https://user-images.githubusercontent.com/65226231/140736591-74e7389d-6c02-4408-9a24-cc93d6bcd8d1.png)
Might need more testing, but it happened to both the big and small rosh.

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **7** days with label "needs confirmation".  
It will be **closed** automatically after **7** days if this issue stays inactive.

**Comment by NocturneOfShadows** [comment]
Ok, so it doesn't perma aggro, but the aggro duration is clearly waaay longer than ult/debuff duration
