### ISSUE TITLE
Curse of Endless Torment applies modifies without the modifier talent

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/pathfinder_issues#142]
![image](https://user-images.githubusercontent.com/63279022/140845488-bf75e1d0-ddf7-47c4-a13e-6ce8b694f2cd.png)

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **7** days with label "needs confirmation".  
It will be **closed** automatically after **7** days if this issue stays inactive.
