### ISSUE TITLE
Stop illusions / summons from triggering the 'multiple players heroes' state that enables some unit skills

### ISSUE THREAD

**Issue by CarnedaN** [arcadia-redux/pathfinder_issues#144]
Example was given with jug's illusions but same thing should be happening with manta and other heroes illusions / summons if it's not already the case

**Comment by Draze22** [comment]
What's the multiple players heroes state?

**Comment by CarnedaN** [comment]
it's just not boss, rooms like WK/Phoenix,... have a special behavior when there's only one player left 
Like WK won't stun a solo/last survivor player

**Comment by Snoresville** [comment]
give me a list and i'll fix it down to the letter
