### ISSUE TITLE
Mystic Snake global bounce range talent can bounce to other rooms

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/pathfinder_issues#157]
![image](https://user-images.githubusercontent.com/63279022/141751197-5ab83ad1-7828-4efe-a76c-98dcea23d974.png)

**Comment by SanctusAnimus** [comment]
Well what do you think "global" means lol. Although it's a bug outside of Snake scope, means there's alive enemy in previous room, which should never happen

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **7** days with label "needs confirmation".  
It will be **closed** automatically after **7** days if this issue stays inactive.
