### ISSUE TITLE
Curse of Endless Torment can spawn Gorgon Poles from destroying boxes

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/pathfinder_issues#162]
This seems pretty dumb.

**Comment by SanctusAnimus** [comment]
Wait isn't it in conflict with #161 ?

**Comment by SanctusAnimus** [comment]
Poles proc from death of any creature that have taken damage from Medusa in last 1.5s, actual killer doesn't matter, made that way by Friday guideline

**Comment by SanctusAnimus** [comment]
So? Split shot no longer works on boxes, you have to deliberately target them. Moreover, there are quite a few rooms where you don't have anything else to spawn Poles from (especially on bosses)

**Comment by SanctusAnimus** [comment]
![image](https://user-images.githubusercontent.com/43399078/141977821-34410d7b-04f6-42f4-9677-95fc0f63956d.png)
like on these dudes, if i disable poles from boxes, shard becomes absolutely useless? they don't spawn anything at all. Same goes for void spirit boss etc

**Comment by Draze22** [comment]
That's true, alright I'm happy to leave it.
