### ISSUE TITLE
Icarus Dive bug

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/pathfinder_issues#166]
![image](https://user-images.githubusercontent.com/63279022/142571682-9611d850-40aa-4135-9b5a-48bddc43c75b.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/142949373-5ff26bb3-d0d6-4686-b698-e516202f6d70.png)

**Comment by DemoTheG** [comment]
To elaborate: It is triggered by attacking units in the currently active room by attacking them while Phoenix is in a previous room (it does not zap you when you dive into a room that has not loaded yet)
