### ISSUE TITLE
Wand of the Brine mana regen and Carapace of Qualdin Health Regen don't work

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/pathfinder_issues#169]
![image](https://user-images.githubusercontent.com/63279022/143326353-e394757f-1ffe-456d-94a4-7dc26c655c66.png)

**Comment by lovro-m** [comment]
Percentage mana and health regen are obsolete in the game. We can add flat values instead?

**Comment by fcalife** [comment]
Could we circumvent that by simply making the flat values return something like 0.01 * self:GetParent():GetMaxHealth() (whatever the proper number is), and so on?

**Comment by lovro-m** [comment]
sure

**Comment by lovro-m** [comment]
It's not exactly percentage from self:GetParent():GetMaxHealth() but from already flat values which is deprecated. I think I'll make an infinite loop with I take current mana regen and try to apply percentage to it.

**Comment by lovro-m** [comment]
I tried this thing but for some reason GetManaRegen() returns wrong values so idk what else to do about this.

function modifier_item_wand_of_the_brine:GetModifierConstantManaRegen( params )
	if self.lock then return 0 end

	self.lock = true
	local mana_regen = 0.01 * self:GetParent():GetManaRegen() * self.bonus_mana_regen_pct
	self.lock = false

	return mana_regen
end

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **7** days with label "needs confirmation".  
It will be **closed** automatically after **7** days if this issue stays inactive.
