### ISSUE TITLE
Wish there was a way to turn off skills, like right click or something

### ISSUE THREAD

**Issue by diaomaoxi** [arcadia-redux/pathfinder_issues#19]
There are special circumstances in which the player may wish to turn abilities off
such like:

Ogre-Magi has IT'S ALL OGRE NOW, but the monster has You've got mail buff.
Dazzle has MASS BURIAL,but he doesn't want the enemy nearby becom chicken because he's going to use Blade Mail.
Jakiro has ICE-SOLATION PROTOCOL,but he doesn't need the walls,he just want to run away.
Ursa has CONCEALED, but in some stage he doesn't want to be invisibility ,he want to be tank.
Omniknight has CONDEMNATION,and monsters with You've got mail  comes.
Jugg has MEAT SPIN,but some times he just want a original Bladefury.
Tidehunte has RAZOR SHORE,after it proc,all the enemies in the room rushed at him, and the team was destroyed

**Comment by Snoresville** [comment]
you dont want to commit to the choices that dictate your entire performance in a run?
