### ISSUE TITLE
Presence of the Dark Lord's armor reduction shard doesn't work

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/pathfinder_issues#193]
![image](https://user-images.githubusercontent.com/63279022/145717478-edaef8e4-71e4-4535-88ef-28da177b0619.png)

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **7** days with label "needs confirmation".  
It will be **closed** automatically after **7** days if this issue stays inactive.
