### ISSUE TITLE
Several Bristleback Shards display the wrong value

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/pathfinder_issues#24]

**Comment by fcalife** [comment]
@Draze22 are their descriptions hardcoded?

**Comment by Draze22** [comment]
> @Draze22 are their descriptions hardcoded?

Seems like it.

**Comment by Snoresville** [comment]
which ones? i dont know what to fix if i dont know what shards are wrong

**Comment by Draze22** [comment]
I'll start gathering a list.

**Comment by Draze22** [comment]
Zeus's Static Field % damage.

**Comment by Draze22** [comment]
Phantom Assassin's crit chance shard.

**Comment by Snoresville** [comment]
reason: seems as if it's been fixed by someone
