### ISSUE TITLE
Perk issues

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/pathfinder_issues#26]
Some Perks display at 10x their actual value:

![image](https://user-images.githubusercontent.com/63279022/136191313-b297a134-e983-47e7-a6a8-771018859432.png)

![image](https://user-images.githubusercontent.com/63279022/136191564-8377c2cd-502e-4607-a062-05a06c38acc4.png)

**Comment by fcalife** [comment]
Fixed
