### ISSUE TITLE
Two of Hoodwink's Scurry Legendary Shards might be able to crash the game

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/pathfinder_issues#30]
![image](https://user-images.githubusercontent.com/63279022/135780412-9a40f73a-2d0f-43ea-bac0-1946e364e619.png)

![image](https://user-images.githubusercontent.com/63279022/135780514-c6af3e73-71bb-4ac5-986a-5618f7da838c.png)

![image](https://user-images.githubusercontent.com/63279022/135780611-3bba492d-9534-4acd-b824-9dafd5c88a6e.png)

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **7** days with label "needs confirmation".  
It will be **closed** automatically after **7** days if this issue stays inactive.
