### ISSUE TITLE
Mirana one shots Phoenix during his Supernova form

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/pathfinder_issues#4]
Opened from Discord by **Snoresville#2486**
Follow the conversation [here](https://discord.com/channels/501306949434867713/877534831918067742/895310891325722644)

**Comment by Snoresville** [comment]
fixed in https://github.com/arcadia-redux/pathfinders/commit/83232f2c742198bc50eab564786ce33ab922d541
