### ISSUE TITLE
The lives of the hero should be behind the shard menu, not overlapping it

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/pathfinder_issues#60]
![image](https://cdn.discordapp.com/attachments/876970971007971358/893914234449199184/unknown.png)

Opened from Discord by **darklord#6168**
Follow the conversation [here](https://discord.com/channels/501306949434867713/876970971007971358/893914234675683388)

**Comment by fcalife** [comment]
either fixed or no longer relevant
