### ISSUE TITLE
Add family perk

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/pathfinder_issues#67]
requires making tier 4 perk as like the other mods

Opened from Discord by **darklord#6168**
Follow the conversation [here](https://discord.com/channels/501306949434867713/876970971007971358/898958268792189029)

**Comment by Draze22** [comment]
Family perks would be too strong in Pathfinder's purely because of allies getting partial benefit. You're always going to have a few players on each team that highly benefit from any perk and therefore almost every player will quickly realise they should always choose Family perks.

**Comment by fcalife** [comment]
I strongly agree with Draze.

This would also strongly incentivize restarting games to reroll until you get a good perk.
