### ISSUE TITLE
Add an afk/disconnect timer that allows the other players to progress without them

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/pathfinder_issues#71]
Quite a few people are complaining about afk/disconnected players that haven't abandoned yet preventing them from continuing. Afaik this only happens when all 4 players have to stand on a button to get to the next room. 

We could instead add a 1-5 minute timer for the buttons to the next room after which any player not standing on a button is considered abandoned.

**Comment by fcalife** [comment]
The current fix only cares about abandoned players, making it possible to get stuck in trap rooms if a player disconnects without abandoning.

We need to track players' disconnected time, and flag them as abandoned after 3 minutes of being disconnected. If a player is flagged as abandoned, the others should be able to progress without them. This should also be valid for the platforms right before aghanim's boss room.

**Comment by Snoresville** [comment]
Current fix is to make all heroes teleport to the room after the room finishes if they are not in it for whatever reason

resolved in https://github.com/arcadia-redux/pathfinders/commit/596cf6f309ce7f868e45307fc5948b644b53eeaa
