### ISSUE TITLE
Dazzle can easily get 100% uptime on Shallow Grave

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/pathfinder_issues#75]
![image](https://user-images.githubusercontent.com/63279022/137834410-ac4d901c-0e59-4e86-ad80-90218abd57b7.png)

**Comment by Snoresville** [comment]
level 3 bad juju + octarine core is already 75% cdr, normal duration for shallow grave is 4.5 and cooldown is 20, so dazzle could conveniently have one more minor shard in either bad juju cdr or shallow grave duration to get 100% uptime

**Comment by Snoresville** [comment]
should be, it was fixed to be stacking a while ago

**Comment by fcalife** [comment]
Changing this is not necessary right now
