### ISSUE TITLE
Degen Aura Displays a much larger radius than it should

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/pathfinder_issues#76]
Fixing this is a low priority.

![image](https://user-images.githubusercontent.com/63279022/137837307-cc615732-4b4d-454a-83a8-191ed891ccae.png)

**Comment by Draze22** [comment]
Reverse Polarity doesn't show it's radius being increased when you get radius upgrades.

![image](https://user-images.githubusercontent.com/63279022/137839669-c372fb27-b949-426b-9a0b-a8beb6c0e274.png)

**Comment by fcalife** [comment]
Fixed

**Comment by fcalife** [comment]
@ZLOY5 please claim this one for yourself
